### PR TITLE
Chore/update dockerimage

### PR DESCRIPTION
**Pull request by siljekristensen**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- Updated node version from 14.19 to 14.20. 
- Changed the deploy image from using a Debian based image (10.12) to a Alpine (3.16.2) based image. This takes us from `Total: 136 (UNKNOWN: 0, LOW: 84, MEDIUM: 12, HIGH: 30, CRITICAL: 10)` known vulnerabilities in that layer of the image to `Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)`

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

**Status**

- [ ] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [x] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Review by Julusian — APPROVED** [review]
I think that we needed `-slim` in the past because in the first stage we were compiling a native binding. But as that dependency has been removed I see no reason to keep using `-slim`.

At some later time, we should look at whether we need first stage to be the full image or whether it would work with alpine too

**Comment by jstarpl** [comment]
@Julusian @siljekristensen Should we also modify `Dockerfile.circle` in the same fashion? I think that's what being used to push public images to DockerHub? No reason to have those two be that different.

**Comment by siljekristensen** [comment]
> I think that we needed `-slim` in the past because in the first stage we were compiling a native binding. But as that dependency has been removed I see no reason to keep using `-slim`.
> 
> At some later time, we should look at whether we need first stage to be the full image or whether it would work with alpine too

I tested building with Alpine too, but that didn't seem to work with Meteor (because it needs glibc). But I think building in a "larger" image and then just copying what is needed to a smaller production image should be fine.

**Comment by siljekristensen** [comment]
> @Julusian @siljekristensen Should we also modify `Dockerfile.circle` in the same fashion? I think that's what being used to push public images to DockerHub? No reason to have those two be that different.

Ah, I didn't realize how it was being used. I can update this PR.

**Pull request merged**
